Revert "ini_set no longer allowed when session has already been started"
this did not help:

Zend_Session_Exception: Unknown option: name = SOMESESSIONID

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php:227

This reverts commit 10c5fdf8dac22f280a952d8ac54b4106d86081af.