PHPUnit - mcrypt deprecated since php >= 7.1 so skip test (#272)
* phpunit - Skip test use method mcrypt_* on php >= 7.1

mcrypt_* function has been DEPRECATED as of PHP 7.1.0 and REMOVED as of PHP 7.2.0. Relying on this function is highly discouraged.

* phpunit - skip run Openssl test on php >= 8.0

since php 8.0 will raise something like that 'ArgumentCountError: openssl_seal() expects at least 5 arguments, 4 given'

* phpunit - ignore temp file make by test

* phpunit - comment out Zend_CurrencyTest suite

* phpunit - comment out Zend_Crypt_MathTest Suite

* php 8.1 - fix deprecated message

TypeError: count(): Argument #1 () must be of type Countable|array, null given

PHP Deprecated:  DOMDocument::__construct(): Passing null to parameter #2 () of type string is deprecated

* phpunit - correctly Zend_Feed_* test suite and turn on Zend_Feed_AllTests suite

* phpunit - back compatibility exception message for php < 8.0

* git - ignore temp file make by unittest

* phpunit - back compatibility exception message for php < 8.0 for Zend_ProgressBar_Adapter_ConsoleTest

* php <= 7.4 - fix warning 'A non well formed numeric value encountered'

* github action - add step run phpunit on php 7.4

* github action - run phpunit on php 8.1, 8.0, 8.4 parallel